# Generated by Django 4.0.6 on 2022-07-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
