# Generated by Django 4.0.6 on 2022-07-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_venue_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-status']},
        ),
    ]
