# Generated by Django 4.0.6 on 2022-07-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_venue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
