# Generated by Django 4.0.6 on 2022-09-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_venue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('setTime', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('foh', models.CharField(blank=True, max_length=150)),
                ('fohConfirmed', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=150)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.band')),
            ],
        ),
    ]
