# Generated by Django 4.0.6 on 2022-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_gig_foh_alter_gig_fohconfirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gig',
            name='fohConfirmed',
            field=models.CharField(max_length=50, verbose_name='Is the sound person confirmed?'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='setTime',
            field=models.CharField(max_length=50, verbose_name='Set Time'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
