# Generated by Django 4.0.6 on 2022-09-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_gig_address_alter_gig_fohconfirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City (Required)'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='date',
            field=models.DateField(verbose_name='Date (Required)'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name (Required)'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State (Required)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=150, verbose_name='City (Required)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name (Required)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=150, verbose_name='State (Required)'),
        ),
    ]
