# Generated by Django 4.0.6 on 2022-09-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
    ]
