# Generated by Django 4.0.6 on 2022-09-26 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='batchCost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothing'), ('MU', 'Music'), ('ME', 'Merchandise')], default='CL', max_length=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='currentQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='dateBought',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='dateSold',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default=0, max_length=150, verbose_name='Name (Required)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sellingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
